version: '3.7'

services:
  web:
    image: nginx:alpine
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:80"
    restart: always
    networks:
      - webapplication6
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
        - SA_PASSWORD=password
        - ACCEPT_EULA=Y
    restart: always
    networks:
      - webapplication6

networks:
  webapplication6:
